### ISSUE TITLE
Build "new" modal

### ISSUE THREAD

**Issue by mmontesanonyc** [nychealth/EH-dataportal#6] opened 2022-07-26 13:03 UTC
On launch, we'll need a "this is a new site" modal that tells people that this is new and asks them to sign up for our email list (google docs form). 
- [Leaflet conditional modal](https://leafletjs.com/reference.html)
- [Session storage](https://developer.mozilla.org/en-US/docs/Web/API/Window/sessionStorage)

First: don’t show the modal if there’s an existing session and it’s been less than 24 hours since the session started; else show the modal:
```
if (sessionStorage) {
  var session = sessionStorage.getItem(SESSION_KEY);
  // open the dialog only every 24 hours
  if (session && Date.now() - session < ONE_DAY_MILLI_SEC) {
    return; // stops eval
  }
}
```

Second: Set a session storage value with the current date and time, and some key:

```
if (sessionStorage) {

  sessionStorage.setItem(SESSION_KEY, Date.now());

}
```

So we just wrap the modal code in a function like [here](https://leafletjs.com/dialog/dialog.js), then call it on every page (maybe by adding to head.html or baseof.html?), and we should be set.

**Comment by cgettings** [comment] 2022-07-27 03:18
attn @mmontesanonyc 

Not working correctly on pages that are not the home page. The page is darkening, but the dialog isn't popping up. But, it works as intended on the home page.

**Comment by mmontesanonyc** [comment] 2022-07-27 11:57
Thanks for getting this started! I tweaked the modal text. 

What's the best way to test this given the session storage thing - just change that to a small value for testing?
Strange that it doesn't work on other pages from baseof. I tried sticking it into the js_bottom partial to see if that would work either but it doesn't.

**Comment by mmontesanonyc** [comment] 2022-07-27 16:50
Another thing to think about for the modal is to wrap it in a Hugo environment variable, so that it builds one way for dev ("This is our staging site, click here for production.") and another way for production ("Welcome to our new site, sign up for our email list.")

**Comment by cgettings** [comment] 2022-07-27 18:08
@mmontesanonyc It works! And it tells you in the console why it's showing or hiding the modal. Solution ended up just using the previous modal, with some bootstrap-modal-specific JavaScript.

**Comment by mmontesanonyc** [comment] 2022-07-27 18:29
Awesome! wtg. I'm going to tweak styles a tiny bit.

**Comment by mmontesanonyc** [comment] 2022-07-27 18:32
re: environment variables, we could just wrap `conditional-modal.html` in an environment variable ([like this](https://discourse.gohugo.io/t/questions-about-hugo-environment-variables/17865/9)) to create environment-specific modals. No need to do that now but it's probably something we should do in the coming month or so.

**Comment by mmontesanonyc** [comment] 2022-08-09 13:20
This is all set, right? [All in here](https://github.com/nychealth/EH-dataportal/pull/12)?

**Comment by cgettings** [comment] 2022-08-09 15:09
Yep, all there. Not sure I've merged the changes into main / prod.

**Comment by mmontesanonyc** [comment] 2022-08-09 15:10
> Yep, all there. Not sure I've merged the changes into main / prod.

That's fine. We don't really need to 'assemble' main/prod at this point. When we get closer to launch, we can, but for now we can basically ignore it while we finalize using development.

**Comment by cgettings** [comment] 2022-08-12 00:49
I want to enable closing the modal on `esc` or `enter`

**Comment by mmontesanonyc** [comment] 2022-08-12 11:27
This is the modal from the older version - esc closes it. I think I had pulled this specifically from a source on accessible modals. The different is (just, I think) that button in `modal-header` with the `data-dismiss="modal"` attribute. 


```
<div class="modal" tabindex="-1" role="dialog" id="prototypeModal">
  <div class="modal-dialog modal-dialog-centered" role="document">
  <div class="modal-content">
  <div class="modal-header">
  <h5 class="modal-title">This is a prototype.</h5>
  <button type="button" class="close" data-dismiss="modal" aria-label="Close">
  <span aria-hidden="true">&times;</span>
  </button>
  </div>
  <div class="modal-body">
  <p>Welcome to the new Environment & Health Data Portal. This prototype is a work in progress. That means that not all of the information, data, or content is final.</p>
  <p>But, feel free to click around and explore.</p>
  </div>
  <div class="modal-footer">
  <button type="button" class="btn btn-secondary" data-dismiss="modal">Close</button>
  </div>
  </div>
  </div>
</div>
```

**Comment by cgettings** [comment] 2022-08-12 13:57
Turns out it already works on `esc`. Maybe I had dev tools open. It would be nice for it to work on enter, but that's not really important. Closing this again.

**Closed by cgettings** 2022-08-12 13:57 UTC
